# Generated by Django 4.2.4 on 2023-08-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_remove_tweets_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweets",
            name="author",
            field=models.ForeignKey(
                default="<function now at 0x7fba7eb06480>",
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweets",
            name="title",
            field=models.CharField(
                default="<function now at 0x7fba7eb06480>", max_length=50
            ),
            preserve_default=False,
        ),
    ]
