# Generated by Django 4.2.4 on 2023-08-11 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_tweets_author_tweets_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweets",
            name="title",
        ),
    ]
