# Generated by Django 4.2.4 on 2023-08-12 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_remove_tweets_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweets",
            name="author",
        ),
    ]
